### ISSUE TITLE
Integration of data deposition timelines and compliance

### ISSUE THREAD

**Issue by jaybee84** [Sage-Bionetworks/projectlive.modules#1]

**Comment by jaybee84** [comment]
More info here: https://github.com/Sage-Bionetworks/projectLive/issues/77#issuecomment-758898104

**Comment by jaybee84** [comment]
[Incoming Data Table ](https://www.synapse.org/#!Synapse:syn23364404/tables/) now has `fileFormat` column as a STRING_LIST

**Comment by jaybee84** [comment]
Reposting this here for easy referral:

The vision for the plot:

In the Study Summary Page, a study is selected and the following "Milestone Report Box" (containing a bar plot) emerges in addition to the other plots:

Top level dropdown list to choose a certain milestone [This milestone number and the associated date of upload is pulled in from Incoming Data Table]
For a chosen milestone, use date_of_upload column to make a bar plot with:
1st bar = fileFormats + min_upload_estimate from Incoming Data Table (data expected)
2nd bar = use the date_of_upload as today's date and count files uploaded within "X number of Days (+/-)", bar of count of files for each fileFormat [fill = fileFormat, y-axis = count] (use "New Submissions Module logic to power this)
Include a field for user to state the "X number of days" desired for viewing

**Comment by jaybee84** [comment]
Proposed  workflow is:
- match studyID between Files and https://www.synapse.org/#!Synapse:syn23364404/tables/
- pull in date_estimateupload
- use date_estimateupload as today's date  as used in "new submissions" module
- Pull all files with createdOn within "X number of days" of date_estimateupload in the matched studyID
- bar plot-  bar#2 == counts of files in #4 with fill color == fileFormat

**Comment by jaybee84** [comment]
Title for second box: `Researcher reported milestone upload`
Viz for second box:

Table for Left hand plot (Expected data for this milestone)
```
Incoming Data Table %>%
filter (studyID, reportMilestone) %>%
plot (fileformat)
```

Table for Right hand plot (Researcher reported data for this milestone)
```
Portal Files Table %>%
filter (studyID, reportMilestone) %>%
plot (fileformat)
```

**Comment by jaybee84** [comment]
Title for first box (visualization that you made already) : `Internal milestone tracker`

**Comment by andrewelamb** [comment]
@jaybee84 Can you elaborate on these two plots?

**Comment by jaybee84** [comment]
Title for second box: `Researcher reported milestone upload`

X axis label for second box: 
Left hand side plot: `Files expected for this milestone`
Right hand side plot : `Files annotated with this milestone`

Y axis label: `Number of files`

TODO: Add drop down menu for the milestone selection instead of table with date

**Comment by jaybee84** [comment]
Title for first box: `Internal milestone tracker`

Y axis label : `Number of files`
X axis label : `Types of files`
