### ISSUE TITLE
Make this github repository a `template` so that other github repos can be created easily from this one

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/projectlive.modules#25]
**Is your feature request related to a problem? Please describe.**
There is a feature in `Settings` where you can make this repository a "template".  This will make creating github repos from this one much easier.  An example looks like this:

![image](https://user-images.githubusercontent.com/10556275/120320350-a7635800-c314-11eb-9ef9-0103f26e9ae4.png)

**Comment by andrewelamb** [comment]
https://github.com/Sage-Bionetworks/projectlive_template
