### ISSUE TITLE
Change color of bars in a plot, download plot data as an excel file

### ISSUE THREAD

**Issue by jaybee84** [Sage-Bionetworks/projectlive.modules#29]
**Is your feature request related to a problem? Please describe.**
I want to change the color of the bars in the plots and also want to download the data in the plot as a table (e.g. excel file)

**Describe the solution you'd like**
I would like to have a button near each plot like `download the data in this plot as excel` 
I would also like a UI near the plot where I can change the color of the bars in the plot.

**Describe alternatives you've considered**
Asking a Sage insider to send me the data as an excel sheet. 

**Additional context**
This feature was requested by the program manager for NTAP

**Comment by andrewelamb** [comment]
I've started #31 for the Bar color UI
