### ISSUE TITLE
Plot bar color UI

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/projectlive.modules#31]
Is your feature request related to a problem? Please describe.
I want to change the color of the bars in the plots

Describe the solution you'd like
I would also like a UI near the plot where I can change the color of the bars in the plot.

**Comment by jaybee84** [comment]
I spent some time on this yesterday and was able to add in the color button UI to the plot_function.R. I do not have permission to push to this repo, so got a fatal error while starting a PR. If you add me to this repo, I am happy to push in my code :) .. just wanted to mention in case that would save you some time :)

**Comment by andrewelamb** [comment]
@jaybee84 That would be great! The CI testing isn't working on the repo, could you push to a branch and create a PR to main? I can run tests locally then. You should have permissions to do that now.
